version: '2'

services:
    meerkat-db:
        container_name: "wayne-db"
        image: "postgres:11.5"
        volumes:
            - "wayne:/var/lib/postgresql/data"
            - "/etc/timezone:/etc/timezone:ro"
        ports:
            - "5433:5432"
        environment:
            - "POSTGRES_DB=wayne"
            - "POSTGRES_USER=user"
            - "POSTGRES_PASSWORD=password"
        networks:
            - "wayne_network"

volumes:
    wayne:
        driver: "local"

networks:
    wayne_network: