version: '3'

services:

    wayne-app:
        container_name: "wayne-app"
        build: .
        volumes:
            - .:/data/www
        depends_on:
          - wayne-db
        ports:
            - "8000:8000"

    wayne-db:
        container_name: "wayne-db"
        image: "postgres:11.5"
        volumes:
            - "db-data:/var/lib/postgresql/data"
            - "/etc/timezone:/etc/timezone:ro"
        environment:
            - "POSTGRES_DB=wayne_db"
            - "POSTGRES_USER=user"
            - "POSTGRES_PASSWORD=password"

volumes:
    db-data:
        driver: "local"
